### ISSUE TITLE
slick.js missing from thirdpartylilbs.xml

### ISSUE THREAD

**Issue by danmarsden** [avetica/moodle-mod_stackview#1]
note - this is a blocker for plugins db approval

**Comment by luukverhoeven** [comment]
@danmarsden Thanks for the review. Added slick.js to thirdpartylilbs.xml

**Comment by danmarsden** [comment]
hey @luukverhoeven - looks like you've got the wrong path in the thirdpartylibs.xml file for the slick lib so it's not being filtered out by the codechecker reports. - you've put it in as amd/slick.js but it should be amd/src/slick.js

it is listed though - so it's not a blocker for approval, but will be good to fix up to drop the number of errors/warnings that show in the plugins db page.

thanks!

**Comment by luukverhoeven** [comment]
Hi @danmarsden, thanks for the check.
I updated the https://github.com/avetica/moodle-mod_stackview/blob/master/thirdpartylibs.xml
